replicaCount: 1

image:
  repository: harshavardhanvp/my-python-app
  tag: v1

service:
  type: ClusterIP
  port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
 
